[package]
name = "sunset-sftp"
version = "0.1.1"
edition = "2024"

[dependencies]
sunset = { version = "0.3.0", path = "../" }
sunset-async = { path = "../async", version = "0.3" }
sunset-sshwire-derive = { version = "0.2", path = "../sshwire-derive" }


embedded-io-async = "0.6"
num_enum = {version = "0.7.4"}
paste = "1.0"
log = "0.4"
