[package]
name = "sunset-sshwire-derive"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/mkj/sunset"
license = "0BSD"
description = "Derive macros for Sunset SSH packet encoder/decoder"

[lib]
proc-macro = true

[dependencies]
virtue = "0.0.17"
